services:
  db:
    image: mysql:8.0
    container_name: pictures-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: Pictures
      MYSQL_USER: mbit
      MYSQL_PASSWORD: mbit
      MYSQL_ROOT_PASSWORD: mbit
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro

  api:
    build: .
    container_name: pictures-api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: Pictures
      MYSQL_USER: mbit
      MYSQL_PASSWORD: mbit
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      IMAGES_DIR: /opt/app/images
    ports:
      - "8080:80"
    volumes:
      - ./.docker/images:/opt/app/images
      - ./credentials.json:/opt/app/credentials.json:ro
