services:
  db:
    image: mysql:8.0
    container_name: pictures-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pictures
      MYSQL_USER: mbit
      MYSQL_PASSWORD: mbit
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro

